### PR TITLE
Add validations package

### PR DESCRIPTION
**Pull request by xtuc**
Moved the validations into their own package.

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
Minor point - I'd call this package 'validation' rather than 'validations'. Otherwise, looks good to me!

**Comment by xtuc** [comment]
Ok @ColinEberhardt I renamed it. I should have waited before publishing it (https://www.npmjs.com/package/@webassemblyjs/validations will remain for ever).

**Comment by xtuc** [comment]
Waiting for your review @maurobringolf since it's against your branch.

**Comment by maurobringolf** [comment]
Thank you! I also prefer the name validation, closer to the spec :+1:

**Pull request merged**
