### PR TITLE
First draft of parens-less instructions

### PR DESCRIPTION
**Pull request by maurobringolf**
I literally just tried to pass a few examples without breaking anything else. Im pretty sure this will need further tweaking.

### CODE REVIEW

**Comment by xtuc** [comment]
Closes #339

**Comment by xtuc** [comment]
I've fixed the flow errors on master, have you looked at them or ignored because of "references"?

Otherwise LGTM, we can merge an early version if you want.

**Comment by maurobringolf** [comment]
I saw your fixes and rebased ontop of them, thanks for that. There are other errors now due to the additional vector property on `Array<Valtype>`. I am trying to come up with a nicer solution that flow agrees with.

**Comment by xtuc** [comment]
Can we merge this? We can iterate on that later

**Comment by maurobringolf** [comment]
Fine with me, I've had a go at the vector but couldnt get flow to agree.

**Comment by xtuc** [comment]
ah no the CI :sob:

**Comment by xtuc** [comment]
Thanks @maurobringolf

**Pull request merged**
