### PR TITLE
implement table parser

### PR DESCRIPTION
**Pull request by sendilkumarn**

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
Nice job! You've got a few linting errors which is causing the CI to fail. When testing locally run the following:

~~~
$ npm run test-ci
~~~

This will ensure that eslint / flow-typing tests are also run.

**Comment by xtuc** [comment]
Sorry I've broke your PR! Since #276 it seems that some tests are failing and I'm working on fixed them.

**Comment by xtuc** [comment]
I somehow messed up with my local git, i'm going to merge it and fix it on master.

**Comment by xtuc** [comment]
Fixed in https://github.com/xtuc/webassemblyjs/commit/64e0a5d28fe9ef260ce01dc79454f6813fd3d149.

Thanks @sendilkumarn !

**Pull request merged**
