### PR TITLE
Nan and Inf support in wasm-parser

### PR DESCRIPTION
**Pull request by maurobringolf**
I still need to fix the f64 case, there are some issues in the wast-parser.

### CODE REVIEW

**Comment by xtuc** [comment]
Would you have the time to try to fix https://github.com/xtuc/webassemblyjs/issues/357? I'm seeing the errosrs in the CI. Otherwise LGTM

**Comment by maurobringolf** [comment]
I'm looking into it after fixing f64. Theres some problems with wast-parser in the f64 case I believe.

**Comment by maurobringolf** [comment]
Implemented and fixed the f64 cases (including `wast-parser`). Remaining errors are these flow reference errors from #357

**Comment by xtuc** [comment]
Thanks

**Pull request merged**
