### PR TITLE
Atomics proposal support

### LINKED ISSUE #393: Implement atomic proposal
- [ ] wasm parser
- [ ] wast printer

See https://github.com/WebAssembly/threads

### PR DESCRIPTION
**Pull request by martianboy**
Fixes #393 for `wasm-parser`, `wast-parser` and `wast-printer`.

### CODE REVIEW

**Review by xtuc — APPROVED** [review]
great work! thanks

**Comment by xtuc** [comment]
I published your changes in :
```
Successfully published:
 - @webassemblyjs/ast@1.11.0
 - @webassemblyjs/cli@1.11.0
 - @webassemblyjs/dce@1.11.0
 - eslint-plugin-webassembly@1.11.0
 - @webassemblyjs/floating-point-hex-parser@1.11.0
 - @webassemblyjs/helper-api-error@1.11.0
 - @webassemblyjs/helper-buffer@1.11.0
 - @webassemblyjs/helper-code-frame@1.11.0
 - @webassemblyjs/helper-compiler@1.11.0
 - @webassemblyjs/helper-flatten-ast@1.11.0
 - @webassemblyjs/helper-fsm@1.11.0
 - @webassemblyjs/helper-numbers@1.11.0
 - @webassemblyjs/helper-test-framework@1.11.0
 - @webassemblyjs/helper-testsuite-runner@1.11.0
 - @webassemblyjs/helper-wasm-bytecode@1.11.0
 - @webassemblyjs/helper-wasm-section@1.11.0
 - @webassemblyjs/ieee754@1.11.0
 - @webassemblyjs/leb128@1.11.0
 - @webassemblyjs/repl@1.11.0
 - @webassemblyjs/utf8@1.11.0
 - @webassemblyjs/validation@1.11.0
 - @webassemblyjs/wasm-edit@1.11.0
 - @webassemblyjs/wasm-gen@1.11.0
 - @webassemblyjs/wasm-opt@1.11.0
 - @webassemblyjs/wasm-parser@1.11.0
 - @webassemblyjs/wasm-text-gen@1.11.0
 - wast-loader@1.11.0
 - @webassemblyjs/wast-parser@1.11.0
 - @webassemblyjs/wast-printer@1.11.0
 - @webassemblyjs/wast-refmt@1.11.0
 - webassemblyjs@1.11.0
```

if you are using webassemblyjs via webpack we will need to bump it there too

**Comment by martianboy** [comment]
@xtuc Thanks a lot, Sven! Yes I am trying to use this in Webpack.

**Comment by xtuc** [comment]
@martianboy  would you be up to open a PR against webpack to bump it? otherwise i'm happy to do it tomorrow

**Comment by martianboy** [comment]
@xtuc Thanks, @sokra created a PR shortly after this was published.

**Comment by xtuc** [comment]
Yeah i noticed too: https://github.com/webpack/webpack/pull/12373 but it seems to be failing. i'll investigate and try to repro

**Comment by sokra** [comment]
yeah, that's pretty weird. I thought this would be a random failure but restarting the CI build didn't fix it. Happens on on MacOS...

For some reason some dependencies can't be snapshot. My first guess would be that there are some files with mtime=0 publish in one of the packages, but I haven't looked into that...

**Comment by sokra** [comment]
ah, seem to be related to some different change. Build log contains some errors...

**Pull request merged**
